name: 'Github Tag Bump'
description: 'Bump and push git tag on merge'
author: 'Denis Korobov'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  new_tag:
    description: 'Generated tag'
  tag:
    description: 'The latest tag after running this action'
branding:
  icon: 'git-merge'  
  color: 'purple'
